// Calendário Oficial Completo da 1ª Liga de Portugal (34 Jornadas / 306 Jogos)
// Gerado para execução autónoma sem dependência de ficheiros externos ou volumes montados
export const OFFICIAL_CALENDAR = [
  {
    "id": "g_j1_est_fcf",
    "round": 1,
    "home_club_id": "EST",
    "away_club_id": "FCF",
    "kickoff_time": "2026-08-07T19:15:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 1,
    "result": "DRAW"
  },
  {
    "id": "g_j1_csm_cpac",
    "round": 1,
    "home_club_id": "CSM",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-08-08T14:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j1_vsc_fca",
    "round": 1,
    "home_club_id": "VSC",
    "away_club_id": "FCA",
    "kickoff_time": "2026-08-08T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 1,
    "result": "AWAY"
  },
  {
    "id": "g_j1_cfea_scp",
    "round": 1,
    "home_club_id": "CFEA",
    "away_club_id": "SCP",
    "kickoff_time": "2026-08-08T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j1_fcp_alv",
    "round": 1,
    "home_club_id": "FCP",
    "away_club_id": "ALV",
    "kickoff_time": "2026-08-09T17:00:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j1_mfc_scb",
    "round": 1,
    "home_club_id": "MFC",
    "away_club_id": "SCB",
    "kickoff_time": "2026-08-09T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j1_gvc_rav",
    "round": 1,
    "home_club_id": "GVC",
    "away_club_id": "RAV",
    "kickoff_time": "2026-08-09T19:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j1_slb_acv",
    "round": 1,
    "home_club_id": "SLB",
    "away_club_id": "ACV",
    "kickoff_time": "2026-08-09T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j1_cdsc_cdn",
    "round": 1,
    "home_club_id": "CDSC",
    "away_club_id": "CDN",
    "kickoff_time": "2026-08-10T19:15:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j2_scp_vsc",
    "round": 2,
    "home_club_id": "SCP",
    "away_club_id": "VSC",
    "kickoff_time": "2026-08-14T19:15:00Z",
    "status": "FINISHED",
    "home_score": 3,
    "away_score": 2,
    "result": "HOME"
  },
  {
    "id": "g_j2_alv_cfea",
    "round": 2,
    "home_club_id": "ALV",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-08-15T14:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j2_acv_cdsc",
    "round": 2,
    "home_club_id": "ACV",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-08-15T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 1,
    "result": "AWAY"
  },
  {
    "id": "g_j2_rav_fcp",
    "round": 2,
    "home_club_id": "RAV",
    "away_club_id": "FCP",
    "kickoff_time": "2026-08-15T19:30:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 2,
    "result": "AWAY"
  },
  {
    "id": "g_j2_scb_gvc",
    "round": 2,
    "home_club_id": "SCB",
    "away_club_id": "GVC",
    "kickoff_time": "2026-08-16T00:00:00Z",
    "status": "POSTPONED",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j2_cdn_est",
    "round": 2,
    "home_club_id": "CDN",
    "away_club_id": "EST",
    "kickoff_time": "2026-08-16T14:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j2_fca_mfc",
    "round": 2,
    "home_club_id": "FCA",
    "away_club_id": "MFC",
    "kickoff_time": "2026-08-16T17:00:00Z",
    "status": "FINISHED",
    "home_score": 4,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j2_fcf_csm",
    "round": 2,
    "home_club_id": "FCF",
    "away_club_id": "CSM",
    "kickoff_time": "2026-08-16T19:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 2,
    "result": "AWAY"
  },
  {
    "id": "g_j2_cpac_slb",
    "round": 2,
    "home_club_id": "CPAC",
    "away_club_id": "SLB",
    "kickoff_time": "2026-08-17T19:15:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 7,
    "result": "AWAY"
  },
  {
    "id": "g_j3_csm_acv",
    "round": 3,
    "home_club_id": "CSM",
    "away_club_id": "ACV",
    "kickoff_time": "2026-08-22T14:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j3_est_rav",
    "round": 3,
    "home_club_id": "EST",
    "away_club_id": "RAV",
    "kickoff_time": "2026-08-22T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 2,
    "result": "AWAY"
  },
  {
    "id": "g_j3_scp_alv",
    "round": 3,
    "home_club_id": "SCP",
    "away_club_id": "ALV",
    "kickoff_time": "2026-08-22T19:30:00Z",
    "status": "FINISHED",
    "home_score": 3,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j3_vsc_cdn",
    "round": 3,
    "home_club_id": "VSC",
    "away_club_id": "CDN",
    "kickoff_time": "2026-08-23T14:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j3_cdsc_fcf",
    "round": 3,
    "home_club_id": "CDSC",
    "away_club_id": "FCF",
    "kickoff_time": "2026-08-23T17:00:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j3_fcp_fca",
    "round": 3,
    "home_club_id": "FCP",
    "away_club_id": "FCA",
    "kickoff_time": "2026-08-23T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j3_gvc_cpac",
    "round": 3,
    "home_club_id": "GVC",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-08-24T19:15:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j4_rav_scp",
    "round": 4,
    "home_club_id": "RAV",
    "away_club_id": "SCP",
    "kickoff_time": "2026-08-28T19:15:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 4,
    "result": "AWAY"
  },
  {
    "id": "g_j4_alv_cdsc",
    "round": 4,
    "home_club_id": "ALV",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-08-29T14:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 1,
    "result": "DRAW"
  },
  {
    "id": "g_j4_fca_csm",
    "round": 4,
    "home_club_id": "FCA",
    "away_club_id": "CSM",
    "kickoff_time": "2026-08-29T14:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j4_acv_fcp",
    "round": 4,
    "home_club_id": "ACV",
    "away_club_id": "FCP",
    "kickoff_time": "2026-08-29T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 3,
    "result": "AWAY"
  },
  {
    "id": "g_j4_cdn_cfea",
    "round": 4,
    "home_club_id": "CDN",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-08-30T14:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 3,
    "result": "AWAY"
  },
  {
    "id": "g_j4_cpac_mfc",
    "round": 4,
    "home_club_id": "CPAC",
    "away_club_id": "MFC",
    "kickoff_time": "2026-08-30T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 1,
    "result": "AWAY"
  },
  {
    "id": "g_j4_fcf_gvc",
    "round": 4,
    "home_club_id": "FCF",
    "away_club_id": "GVC",
    "kickoff_time": "2026-08-30T19:30:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 0,
    "result": "DRAW"
  },
  {
    "id": "g_j4_slb_est",
    "round": 4,
    "home_club_id": "SLB",
    "away_club_id": "EST",
    "kickoff_time": "2026-08-31T19:15:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j4_scb_vsc",
    "round": 4,
    "home_club_id": "SCB",
    "away_club_id": "VSC",
    "kickoff_time": "2026-08-31T19:15:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j5_fcp_mfc",
    "round": 5,
    "home_club_id": "FCP",
    "away_club_id": "MFC",
    "kickoff_time": "2026-09-04T19:15:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j5_cfea_fcf",
    "round": 5,
    "home_club_id": "CFEA",
    "away_club_id": "FCF",
    "kickoff_time": "2026-09-05T14:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j5_alv_scb",
    "round": 5,
    "home_club_id": "ALV",
    "away_club_id": "SCB",
    "kickoff_time": "2026-09-05T17:00:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 2,
    "result": "AWAY"
  },
  {
    "id": "g_j5_csm_slb",
    "round": 5,
    "home_club_id": "CSM",
    "away_club_id": "SLB",
    "kickoff_time": "2026-09-05T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 3,
    "result": "AWAY"
  },
  {
    "id": "g_j5_scp_cdn",
    "round": 5,
    "home_club_id": "SCP",
    "away_club_id": "CDN",
    "kickoff_time": "2026-09-05T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j5_cdsc_rav",
    "round": 5,
    "home_club_id": "CDSC",
    "away_club_id": "RAV",
    "kickoff_time": "2026-09-06T14:30:00Z",
    "status": "FINISHED",
    "home_score": 4,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j5_vsc_cpac",
    "round": 5,
    "home_club_id": "VSC",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-09-06T17:00:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 0,
    "result": "DRAW"
  },
  {
    "id": "g_j5_gvc_acv",
    "round": 5,
    "home_club_id": "GVC",
    "away_club_id": "ACV",
    "kickoff_time": "2026-09-06T19:30:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 1,
    "result": "AWAY"
  },
  {
    "id": "g_j5_est_fca",
    "round": 5,
    "home_club_id": "EST",
    "away_club_id": "FCA",
    "kickoff_time": "2026-09-07T19:15:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 0,
    "result": "DRAW"
  },
  {
    "id": "g_j3_mfc_slb",
    "round": 3,
    "home_club_id": "MFC",
    "away_club_id": "SLB",
    "kickoff_time": "2026-09-09T19:45:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 4,
    "result": "AWAY"
  },
  {
    "id": "g_j3_cfea_scb",
    "round": 3,
    "home_club_id": "CFEA",
    "away_club_id": "SCB",
    "kickoff_time": "2026-09-10T19:15:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j6_cdn_alv",
    "round": 6,
    "home_club_id": "CDN",
    "away_club_id": "ALV",
    "kickoff_time": "2026-09-12T14:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 3,
    "result": "AWAY"
  },
  {
    "id": "g_j6_cpac_fcp",
    "round": 6,
    "home_club_id": "CPAC",
    "away_club_id": "FCP",
    "kickoff_time": "2026-09-12T17:00:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 4,
    "result": "AWAY"
  },
  {
    "id": "g_j6_acv_vsc",
    "round": 6,
    "home_club_id": "ACV",
    "away_club_id": "VSC",
    "kickoff_time": "2026-09-12T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j6_slb_gvc",
    "round": 6,
    "home_club_id": "SLB",
    "away_club_id": "GVC",
    "kickoff_time": "2026-09-13T17:00:00Z",
    "status": "FINISHED",
    "home_score": 3,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j6_fca_cdsc",
    "round": 6,
    "home_club_id": "FCA",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-09-13T17:00:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 2,
    "result": "AWAY"
  },
  {
    "id": "g_j6_fcf_scp",
    "round": 6,
    "home_club_id": "FCF",
    "away_club_id": "SCP",
    "kickoff_time": "2026-09-13T19:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 1,
    "result": "DRAW"
  },
  {
    "id": "g_j6_rav_cfea",
    "round": 6,
    "home_club_id": "RAV",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-09-14T17:45:00Z",
    "status": "FINISHED",
    "home_score": 3,
    "away_score": 3,
    "result": "DRAW"
  },
  {
    "id": "g_j6_mfc_csm",
    "round": 6,
    "home_club_id": "MFC",
    "away_club_id": "CSM",
    "kickoff_time": "2026-09-14T19:15:00Z",
    "status": "FINISHED",
    "home_score": 3,
    "away_score": 1,
    "result": "HOME"
  },
  {
    "id": "g_j6_scb_est",
    "round": 6,
    "home_club_id": "SCB",
    "away_club_id": "EST",
    "kickoff_time": "2026-09-14T19:45:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j7_cdn_fcf",
    "round": 7,
    "home_club_id": "CDN",
    "away_club_id": "FCF",
    "kickoff_time": "2026-09-19T14:30:00Z",
    "status": "FINISHED",
    "home_score": 0,
    "away_score": 4,
    "result": "AWAY"
  },
  {
    "id": "g_j7_gvc_csm",
    "round": 7,
    "home_club_id": "GVC",
    "away_club_id": "CSM",
    "kickoff_time": "2026-09-19T14:30:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 1,
    "result": "DRAW"
  },
  {
    "id": "g_j7_alv_rav",
    "round": 7,
    "home_club_id": "ALV",
    "away_club_id": "RAV",
    "kickoff_time": "2026-09-19T17:00:00Z",
    "status": "FINISHED",
    "home_score": 1,
    "away_score": 0,
    "result": "HOME"
  },
  {
    "id": "g_j7_scp_fca",
    "round": 7,
    "home_club_id": "SCP",
    "away_club_id": "FCA",
    "kickoff_time": "2026-09-19T19:30:00Z",
    "status": "FINISHED",
    "home_score": 2,
    "away_score": 2,
    "result": "DRAW"
  },
  {
    "id": "g_j7_vsc_mfc",
    "round": 7,
    "home_club_id": "VSC",
    "away_club_id": "MFC",
    "kickoff_time": "2026-09-20T14:30:00Z",
    "status": "LIVE",
    "home_score": 0,
    "away_score": 0,
    "result": null
  },
  {
    "id": "g_j7_cfea_acv",
    "round": 7,
    "home_club_id": "CFEA",
    "away_club_id": "ACV",
    "kickoff_time": "2026-09-20T14:30:00Z",
    "status": "LIVE",
    "home_score": 0,
    "away_score": 0,
    "result": null
  },
  {
    "id": "g_j7_cdsc_scb",
    "round": 7,
    "home_club_id": "CDSC",
    "away_club_id": "SCB",
    "kickoff_time": "2026-09-20T17:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j7_est_cpac",
    "round": 7,
    "home_club_id": "EST",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-09-20T17:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j7_fcp_slb",
    "round": 7,
    "home_club_id": "FCP",
    "away_club_id": "SLB",
    "kickoff_time": "2026-09-20T19:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_mfc_gvc",
    "round": 8,
    "home_club_id": "MFC",
    "away_club_id": "GVC",
    "kickoff_time": "2026-10-09T17:45:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_scb_scp",
    "round": 8,
    "home_club_id": "SCB",
    "away_club_id": "SCP",
    "kickoff_time": "2026-10-09T19:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_cpac_cdsc",
    "round": 8,
    "home_club_id": "CPAC",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-10-10T14:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_csm_fcp",
    "round": 8,
    "home_club_id": "CSM",
    "away_club_id": "FCP",
    "kickoff_time": "2026-10-10T17:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_acv_est",
    "round": 8,
    "home_club_id": "ACV",
    "away_club_id": "EST",
    "kickoff_time": "2026-10-10T19:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_rav_cdn",
    "round": 8,
    "home_club_id": "RAV",
    "away_club_id": "CDN",
    "kickoff_time": "2026-10-11T14:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_slb_vsc",
    "round": 8,
    "home_club_id": "SLB",
    "away_club_id": "VSC",
    "kickoff_time": "2026-10-11T17:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_fca_cfea",
    "round": 8,
    "home_club_id": "FCA",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-10-11T19:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j8_fcf_alv",
    "round": 8,
    "home_club_id": "FCF",
    "away_club_id": "ALV",
    "kickoff_time": "2026-10-12T19:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_vsc_csm",
    "round": 9,
    "home_club_id": "VSC",
    "away_club_id": "CSM",
    "kickoff_time": "2026-10-23T19:45:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_cfea_cpac",
    "round": 9,
    "home_club_id": "CFEA",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-10-24T14:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_alv_fca",
    "round": 9,
    "home_club_id": "ALV",
    "away_club_id": "FCA",
    "kickoff_time": "2026-10-24T17:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_gvc_fcp",
    "round": 9,
    "home_club_id": "GVC",
    "away_club_id": "FCP",
    "kickoff_time": "2026-10-24T19:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_est_mfc",
    "round": 9,
    "home_club_id": "EST",
    "away_club_id": "MFC",
    "kickoff_time": "2026-10-25T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_rav_fcf",
    "round": 9,
    "home_club_id": "RAV",
    "away_club_id": "FCF",
    "kickoff_time": "2026-10-25T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_cdn_scb",
    "round": 9,
    "home_club_id": "CDN",
    "away_club_id": "SCB",
    "kickoff_time": "2026-10-25T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_scp_acv",
    "round": 9,
    "home_club_id": "SCP",
    "away_club_id": "ACV",
    "kickoff_time": "2026-10-25T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j9_cdsc_slb",
    "round": 9,
    "home_club_id": "CDSC",
    "away_club_id": "SLB",
    "kickoff_time": "2026-10-26T18:45:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_cpac_scp",
    "round": 10,
    "home_club_id": "CPAC",
    "away_club_id": "SCP",
    "kickoff_time": "2026-10-30T20:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_mfc_cfea",
    "round": 10,
    "home_club_id": "MFC",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-10-31T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_fcp_est",
    "round": 10,
    "home_club_id": "FCP",
    "away_club_id": "EST",
    "kickoff_time": "2026-10-31T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_fca_cdn",
    "round": 10,
    "home_club_id": "FCA",
    "away_club_id": "CDN",
    "kickoff_time": "2026-11-01T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_csm_cdsc",
    "round": 10,
    "home_club_id": "CSM",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-11-01T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_acv_rav",
    "round": 10,
    "home_club_id": "ACV",
    "away_club_id": "RAV",
    "kickoff_time": "2026-11-01T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_scb_fcf",
    "round": 10,
    "home_club_id": "SCB",
    "away_club_id": "FCF",
    "kickoff_time": "2026-11-01T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_slb_alv",
    "round": 10,
    "home_club_id": "SLB",
    "away_club_id": "ALV",
    "kickoff_time": "2026-11-02T20:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j10_gvc_vsc",
    "round": 10,
    "home_club_id": "GVC",
    "away_club_id": "VSC",
    "kickoff_time": "2026-11-02T20:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_fcf_fca",
    "round": 11,
    "home_club_id": "FCF",
    "away_club_id": "FCA",
    "kickoff_time": "2026-11-06T20:45:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_cdn_acv",
    "round": 11,
    "home_club_id": "CDN",
    "away_club_id": "ACV",
    "kickoff_time": "2026-11-07T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_alv_cpac",
    "round": 11,
    "home_club_id": "ALV",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-11-07T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_scp_mfc",
    "round": 11,
    "home_club_id": "SCP",
    "away_club_id": "MFC",
    "kickoff_time": "2026-11-07T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_est_csm",
    "round": 11,
    "home_club_id": "EST",
    "away_club_id": "CSM",
    "kickoff_time": "2026-11-08T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_cdsc_gvc",
    "round": 11,
    "home_club_id": "CDSC",
    "away_club_id": "GVC",
    "kickoff_time": "2026-11-08T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_vsc_fcp",
    "round": 11,
    "home_club_id": "VSC",
    "away_club_id": "FCP",
    "kickoff_time": "2026-11-08T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_rav_scb",
    "round": 11,
    "home_club_id": "RAV",
    "away_club_id": "SCB",
    "kickoff_time": "2026-11-08T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j11_cfea_slb",
    "round": 11,
    "home_club_id": "CFEA",
    "away_club_id": "SLB",
    "kickoff_time": "2026-11-08T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_csm_cdn",
    "round": 12,
    "home_club_id": "CSM",
    "away_club_id": "CDN",
    "kickoff_time": "2026-11-27T20:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_mfc_cdsc",
    "round": 12,
    "home_club_id": "MFC",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-11-28T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_fca_rav",
    "round": 12,
    "home_club_id": "FCA",
    "away_club_id": "RAV",
    "kickoff_time": "2026-11-28T15:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_acv_alv",
    "round": 12,
    "home_club_id": "ACV",
    "away_club_id": "ALV",
    "kickoff_time": "2026-11-28T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_vsc_cfea",
    "round": 12,
    "home_club_id": "VSC",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-11-28T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_gvc_est",
    "round": 12,
    "home_club_id": "GVC",
    "away_club_id": "EST",
    "kickoff_time": "2026-11-29T18:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_fcp_scp",
    "round": 12,
    "home_club_id": "FCP",
    "away_club_id": "SCP",
    "kickoff_time": "2026-11-29T20:30:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_cpac_scb",
    "round": 12,
    "home_club_id": "CPAC",
    "away_club_id": "SCB",
    "kickoff_time": "2026-11-30T20:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j12_slb_fcf",
    "round": 12,
    "home_club_id": "SLB",
    "away_club_id": "FCF",
    "kickoff_time": "2026-11-30T20:15:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_scp_csm",
    "round": 13,
    "home_club_id": "SCP",
    "away_club_id": "CSM",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_cfea_gvc",
    "round": 13,
    "home_club_id": "CFEA",
    "away_club_id": "GVC",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_alv_mfc",
    "round": 13,
    "home_club_id": "ALV",
    "away_club_id": "MFC",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_cdsc_fcp",
    "round": 13,
    "home_club_id": "CDSC",
    "away_club_id": "FCP",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_cdn_slb",
    "round": 13,
    "home_club_id": "CDN",
    "away_club_id": "SLB",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_est_vsc",
    "round": 13,
    "home_club_id": "EST",
    "away_club_id": "VSC",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_rav_cpac",
    "round": 13,
    "home_club_id": "RAV",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_scb_fca",
    "round": 13,
    "home_club_id": "SCB",
    "away_club_id": "FCA",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j13_fcf_acv",
    "round": 13,
    "home_club_id": "FCF",
    "away_club_id": "ACV",
    "kickoff_time": "2026-12-06T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_csm_rav",
    "round": 14,
    "home_club_id": "CSM",
    "away_club_id": "RAV",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_acv_fca",
    "round": 14,
    "home_club_id": "ACV",
    "away_club_id": "FCA",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_gvc_scp",
    "round": 14,
    "home_club_id": "GVC",
    "away_club_id": "SCP",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_cpac_cdn",
    "round": 14,
    "home_club_id": "CPAC",
    "away_club_id": "CDN",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_vsc_alv",
    "round": 14,
    "home_club_id": "VSC",
    "away_club_id": "ALV",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_mfc_fcf",
    "round": 14,
    "home_club_id": "MFC",
    "away_club_id": "FCF",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_est_cdsc",
    "round": 14,
    "home_club_id": "EST",
    "away_club_id": "CDSC",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_slb_scb",
    "round": 14,
    "home_club_id": "SLB",
    "away_club_id": "SCB",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j14_fcp_cfea",
    "round": 14,
    "home_club_id": "FCP",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-12-13T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_rav_slb",
    "round": 15,
    "home_club_id": "RAV",
    "away_club_id": "SLB",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_scb_acv",
    "round": 15,
    "home_club_id": "SCB",
    "away_club_id": "ACV",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_scp_est",
    "round": 15,
    "home_club_id": "SCP",
    "away_club_id": "EST",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_cfea_csm",
    "round": 15,
    "home_club_id": "CFEA",
    "away_club_id": "CSM",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_fcf_fcp",
    "round": 15,
    "home_club_id": "FCF",
    "away_club_id": "FCP",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_alv_gvc",
    "round": 15,
    "home_club_id": "ALV",
    "away_club_id": "GVC",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_cdsc_vsc",
    "round": 15,
    "home_club_id": "CDSC",
    "away_club_id": "VSC",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_cdn_mfc",
    "round": 15,
    "home_club_id": "CDN",
    "away_club_id": "MFC",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j15_fca_cpac",
    "round": 15,
    "home_club_id": "FCA",
    "away_club_id": "CPAC",
    "kickoff_time": "2026-12-20T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_vsc_rav",
    "round": 16,
    "home_club_id": "VSC",
    "away_club_id": "RAV",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_cpac_fcf",
    "round": 16,
    "home_club_id": "CPAC",
    "away_club_id": "FCF",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_fcp_cdn",
    "round": 16,
    "home_club_id": "FCP",
    "away_club_id": "CDN",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_cdsc_cfea",
    "round": 16,
    "home_club_id": "CDSC",
    "away_club_id": "CFEA",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_mfc_acv",
    "round": 16,
    "home_club_id": "MFC",
    "away_club_id": "ACV",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_slb_scp",
    "round": 16,
    "home_club_id": "SLB",
    "away_club_id": "SCP",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_gvc_fca",
    "round": 16,
    "home_club_id": "GVC",
    "away_club_id": "FCA",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_csm_scb",
    "round": 16,
    "home_club_id": "CSM",
    "away_club_id": "SCB",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j16_est_alv",
    "round": 16,
    "home_club_id": "EST",
    "away_club_id": "ALV",
    "kickoff_time": "2026-12-27T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_scb_fcp",
    "round": 17,
    "home_club_id": "SCB",
    "away_club_id": "FCP",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_cfea_est",
    "round": 17,
    "home_club_id": "CFEA",
    "away_club_id": "EST",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_fcf_vsc",
    "round": 17,
    "home_club_id": "FCF",
    "away_club_id": "VSC",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_cdn_gvc",
    "round": 17,
    "home_club_id": "CDN",
    "away_club_id": "GVC",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_rav_mfc",
    "round": 17,
    "home_club_id": "RAV",
    "away_club_id": "MFC",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_fca_slb",
    "round": 17,
    "home_club_id": "FCA",
    "away_club_id": "SLB",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_alv_csm",
    "round": 17,
    "home_club_id": "ALV",
    "away_club_id": "CSM",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_acv_cpac",
    "round": 17,
    "home_club_id": "ACV",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j17_scp_cdsc",
    "round": 17,
    "home_club_id": "SCP",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-01-10T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_fcf_est",
    "round": 18,
    "home_club_id": "FCF",
    "away_club_id": "EST",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_scp_cfea",
    "round": 18,
    "home_club_id": "SCP",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_scb_mfc",
    "round": 18,
    "home_club_id": "SCB",
    "away_club_id": "MFC",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_rav_gvc",
    "round": 18,
    "home_club_id": "RAV",
    "away_club_id": "GVC",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_cpac_csm",
    "round": 18,
    "home_club_id": "CPAC",
    "away_club_id": "CSM",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_cdn_cdsc",
    "round": 18,
    "home_club_id": "CDN",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_alv_fcp",
    "round": 18,
    "home_club_id": "ALV",
    "away_club_id": "FCP",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_acv_slb",
    "round": 18,
    "home_club_id": "ACV",
    "away_club_id": "SLB",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j18_fca_vsc",
    "round": 18,
    "home_club_id": "FCA",
    "away_club_id": "VSC",
    "kickoff_time": "2027-01-17T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_cfea_alv",
    "round": 19,
    "home_club_id": "CFEA",
    "away_club_id": "ALV",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_mfc_fca",
    "round": 19,
    "home_club_id": "MFC",
    "away_club_id": "FCA",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_est_cdn",
    "round": 19,
    "home_club_id": "EST",
    "away_club_id": "CDN",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_fcp_rav",
    "round": 19,
    "home_club_id": "FCP",
    "away_club_id": "RAV",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_slb_cpac",
    "round": 19,
    "home_club_id": "SLB",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_cdsc_acv",
    "round": 19,
    "home_club_id": "CDSC",
    "away_club_id": "ACV",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_csm_fcf",
    "round": 19,
    "home_club_id": "CSM",
    "away_club_id": "FCF",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_gvc_scb",
    "round": 19,
    "home_club_id": "GVC",
    "away_club_id": "SCB",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j19_vsc_scp",
    "round": 19,
    "home_club_id": "VSC",
    "away_club_id": "SCP",
    "kickoff_time": "2027-01-24T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_cpac_gvc",
    "round": 20,
    "home_club_id": "CPAC",
    "away_club_id": "GVC",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_cdn_vsc",
    "round": 20,
    "home_club_id": "CDN",
    "away_club_id": "VSC",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_slb_mfc",
    "round": 20,
    "home_club_id": "SLB",
    "away_club_id": "MFC",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_scb_cfea",
    "round": 20,
    "home_club_id": "SCB",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_fca_fcp",
    "round": 20,
    "home_club_id": "FCA",
    "away_club_id": "FCP",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_fcf_cdsc",
    "round": 20,
    "home_club_id": "FCF",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_acv_csm",
    "round": 20,
    "home_club_id": "ACV",
    "away_club_id": "CSM",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_rav_est",
    "round": 20,
    "home_club_id": "RAV",
    "away_club_id": "EST",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j20_alv_scp",
    "round": 20,
    "home_club_id": "ALV",
    "away_club_id": "SCP",
    "kickoff_time": "2027-01-31T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_csm_fca",
    "round": 21,
    "home_club_id": "CSM",
    "away_club_id": "FCA",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_cdsc_alv",
    "round": 21,
    "home_club_id": "CDSC",
    "away_club_id": "ALV",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_est_slb",
    "round": 21,
    "home_club_id": "EST",
    "away_club_id": "SLB",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_scp_rav",
    "round": 21,
    "home_club_id": "SCP",
    "away_club_id": "RAV",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_fcp_acv",
    "round": 21,
    "home_club_id": "FCP",
    "away_club_id": "ACV",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_cfea_cdn",
    "round": 21,
    "home_club_id": "CFEA",
    "away_club_id": "CDN",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_vsc_scb",
    "round": 21,
    "home_club_id": "VSC",
    "away_club_id": "SCB",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_gvc_fcf",
    "round": 21,
    "home_club_id": "GVC",
    "away_club_id": "FCF",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j21_mfc_cpac",
    "round": 21,
    "home_club_id": "MFC",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-02-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_fca_est",
    "round": 22,
    "home_club_id": "FCA",
    "away_club_id": "EST",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_cdn_scp",
    "round": 22,
    "home_club_id": "CDN",
    "away_club_id": "SCP",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_mfc_fcp",
    "round": 22,
    "home_club_id": "MFC",
    "away_club_id": "FCP",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_scb_alv",
    "round": 22,
    "home_club_id": "SCB",
    "away_club_id": "ALV",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_acv_gvc",
    "round": 22,
    "home_club_id": "ACV",
    "away_club_id": "GVC",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_slb_csm",
    "round": 22,
    "home_club_id": "SLB",
    "away_club_id": "CSM",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_cpac_vsc",
    "round": 22,
    "home_club_id": "CPAC",
    "away_club_id": "VSC",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_fcf_cfea",
    "round": 22,
    "home_club_id": "FCF",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j22_rav_cdsc",
    "round": 22,
    "home_club_id": "RAV",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-02-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_vsc_acv",
    "round": 23,
    "home_club_id": "VSC",
    "away_club_id": "ACV",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_csm_mfc",
    "round": 23,
    "home_club_id": "CSM",
    "away_club_id": "MFC",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_est_scb",
    "round": 23,
    "home_club_id": "EST",
    "away_club_id": "SCB",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_gvc_slb",
    "round": 23,
    "home_club_id": "GVC",
    "away_club_id": "SLB",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_fcp_cpac",
    "round": 23,
    "home_club_id": "FCP",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_scp_fcf",
    "round": 23,
    "home_club_id": "SCP",
    "away_club_id": "FCF",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_cdsc_fca",
    "round": 23,
    "home_club_id": "CDSC",
    "away_club_id": "FCA",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_cfea_rav",
    "round": 23,
    "home_club_id": "CFEA",
    "away_club_id": "RAV",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j23_alv_cdn",
    "round": 23,
    "home_club_id": "ALV",
    "away_club_id": "CDN",
    "kickoff_time": "2027-02-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_rav_alv",
    "round": 24,
    "home_club_id": "RAV",
    "away_club_id": "ALV",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_csm_gvc",
    "round": 24,
    "home_club_id": "CSM",
    "away_club_id": "GVC",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_cpac_est",
    "round": 24,
    "home_club_id": "CPAC",
    "away_club_id": "EST",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_mfc_vsc",
    "round": 24,
    "home_club_id": "MFC",
    "away_club_id": "VSC",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_slb_fcp",
    "round": 24,
    "home_club_id": "SLB",
    "away_club_id": "FCP",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_fcf_cdn",
    "round": 24,
    "home_club_id": "FCF",
    "away_club_id": "CDN",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_scb_cdsc",
    "round": 24,
    "home_club_id": "SCB",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_fca_scp",
    "round": 24,
    "home_club_id": "FCA",
    "away_club_id": "SCP",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j24_acv_cfea",
    "round": 24,
    "home_club_id": "ACV",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-02-28T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_gvc_mfc",
    "round": 25,
    "home_club_id": "GVC",
    "away_club_id": "MFC",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_fcp_csm",
    "round": 25,
    "home_club_id": "FCP",
    "away_club_id": "CSM",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_alv_fcf",
    "round": 25,
    "home_club_id": "ALV",
    "away_club_id": "FCF",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_cdsc_cpac",
    "round": 25,
    "home_club_id": "CDSC",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_scp_scb",
    "round": 25,
    "home_club_id": "SCP",
    "away_club_id": "SCB",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_cfea_fca",
    "round": 25,
    "home_club_id": "CFEA",
    "away_club_id": "FCA",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_vsc_slb",
    "round": 25,
    "home_club_id": "VSC",
    "away_club_id": "SLB",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_cdn_rav",
    "round": 25,
    "home_club_id": "CDN",
    "away_club_id": "RAV",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j25_est_acv",
    "round": 25,
    "home_club_id": "EST",
    "away_club_id": "ACV",
    "kickoff_time": "2027-03-07T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_csm_vsc",
    "round": 26,
    "home_club_id": "CSM",
    "away_club_id": "VSC",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_slb_cdsc",
    "round": 26,
    "home_club_id": "SLB",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_fca_alv",
    "round": 26,
    "home_club_id": "FCA",
    "away_club_id": "ALV",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_acv_scp",
    "round": 26,
    "home_club_id": "ACV",
    "away_club_id": "SCP",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_fcp_gvc",
    "round": 26,
    "home_club_id": "FCP",
    "away_club_id": "GVC",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_cpac_cfea",
    "round": 26,
    "home_club_id": "CPAC",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_scb_cdn",
    "round": 26,
    "home_club_id": "SCB",
    "away_club_id": "CDN",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_fcf_rav",
    "round": 26,
    "home_club_id": "FCF",
    "away_club_id": "RAV",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j26_mfc_est",
    "round": 26,
    "home_club_id": "MFC",
    "away_club_id": "EST",
    "kickoff_time": "2027-03-14T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_cdn_fca",
    "round": 27,
    "home_club_id": "CDN",
    "away_club_id": "FCA",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_vsc_gvc",
    "round": 27,
    "home_club_id": "VSC",
    "away_club_id": "GVC",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_cfea_mfc",
    "round": 27,
    "home_club_id": "CFEA",
    "away_club_id": "MFC",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_alv_slb",
    "round": 27,
    "home_club_id": "ALV",
    "away_club_id": "SLB",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_est_fcp",
    "round": 27,
    "home_club_id": "EST",
    "away_club_id": "FCP",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_cdsc_csm",
    "round": 27,
    "home_club_id": "CDSC",
    "away_club_id": "CSM",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_scp_cpac",
    "round": 27,
    "home_club_id": "SCP",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_rav_acv",
    "round": 27,
    "home_club_id": "RAV",
    "away_club_id": "ACV",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j27_fcf_scb",
    "round": 27,
    "home_club_id": "FCF",
    "away_club_id": "SCB",
    "kickoff_time": "2027-03-21T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_fca_fcf",
    "round": 28,
    "home_club_id": "FCA",
    "away_club_id": "FCF",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_gvc_cdsc",
    "round": 28,
    "home_club_id": "GVC",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_cpac_alv",
    "round": 28,
    "home_club_id": "CPAC",
    "away_club_id": "ALV",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_mfc_scp",
    "round": 28,
    "home_club_id": "MFC",
    "away_club_id": "SCP",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_acv_cdn",
    "round": 28,
    "home_club_id": "ACV",
    "away_club_id": "CDN",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_scb_rav",
    "round": 28,
    "home_club_id": "SCB",
    "away_club_id": "RAV",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_csm_est",
    "round": 28,
    "home_club_id": "CSM",
    "away_club_id": "EST",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_fcp_vsc",
    "round": 28,
    "home_club_id": "FCP",
    "away_club_id": "VSC",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j28_slb_cfea",
    "round": 28,
    "home_club_id": "SLB",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-04-04T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_scp_fcp",
    "round": 29,
    "home_club_id": "SCP",
    "away_club_id": "FCP",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_fcf_slb",
    "round": 29,
    "home_club_id": "FCF",
    "away_club_id": "SLB",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_cdn_csm",
    "round": 29,
    "home_club_id": "CDN",
    "away_club_id": "CSM",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_cdsc_mfc",
    "round": 29,
    "home_club_id": "CDSC",
    "away_club_id": "MFC",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_rav_fca",
    "round": 29,
    "home_club_id": "RAV",
    "away_club_id": "FCA",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_scb_cpac",
    "round": 29,
    "home_club_id": "SCB",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_alv_acv",
    "round": 29,
    "home_club_id": "ALV",
    "away_club_id": "ACV",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_cfea_vsc",
    "round": 29,
    "home_club_id": "CFEA",
    "away_club_id": "VSC",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j29_est_gvc",
    "round": 29,
    "home_club_id": "EST",
    "away_club_id": "GVC",
    "kickoff_time": "2027-04-11T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_slb_cdn",
    "round": 30,
    "home_club_id": "SLB",
    "away_club_id": "CDN",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_fcp_cdsc",
    "round": 30,
    "home_club_id": "FCP",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_csm_scp",
    "round": 30,
    "home_club_id": "CSM",
    "away_club_id": "SCP",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_mfc_alv",
    "round": 30,
    "home_club_id": "MFC",
    "away_club_id": "ALV",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_acv_fcf",
    "round": 30,
    "home_club_id": "ACV",
    "away_club_id": "FCF",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_vsc_est",
    "round": 30,
    "home_club_id": "VSC",
    "away_club_id": "EST",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_cpac_rav",
    "round": 30,
    "home_club_id": "CPAC",
    "away_club_id": "RAV",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_gvc_cfea",
    "round": 30,
    "home_club_id": "GVC",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j30_fca_scb",
    "round": 30,
    "home_club_id": "FCA",
    "away_club_id": "SCB",
    "kickoff_time": "2027-04-18T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_alv_vsc",
    "round": 31,
    "home_club_id": "ALV",
    "away_club_id": "VSC",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_rav_csm",
    "round": 31,
    "home_club_id": "RAV",
    "away_club_id": "CSM",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_cdn_cpac",
    "round": 31,
    "home_club_id": "CDN",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_cfea_fcp",
    "round": 31,
    "home_club_id": "CFEA",
    "away_club_id": "FCP",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_scp_gvc",
    "round": 31,
    "home_club_id": "SCP",
    "away_club_id": "GVC",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_scb_slb",
    "round": 31,
    "home_club_id": "SCB",
    "away_club_id": "SLB",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_cdsc_est",
    "round": 31,
    "home_club_id": "CDSC",
    "away_club_id": "EST",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_fca_acv",
    "round": 31,
    "home_club_id": "FCA",
    "away_club_id": "ACV",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j31_fcf_mfc",
    "round": 31,
    "home_club_id": "FCF",
    "away_club_id": "MFC",
    "kickoff_time": "2027-04-25T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_gvc_alv",
    "round": 32,
    "home_club_id": "GVC",
    "away_club_id": "ALV",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_vsc_cdsc",
    "round": 32,
    "home_club_id": "VSC",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_est_scp",
    "round": 32,
    "home_club_id": "EST",
    "away_club_id": "SCP",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_fcp_fcf",
    "round": 32,
    "home_club_id": "FCP",
    "away_club_id": "FCF",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_mfc_cdn",
    "round": 32,
    "home_club_id": "MFC",
    "away_club_id": "CDN",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_cpac_fca",
    "round": 32,
    "home_club_id": "CPAC",
    "away_club_id": "FCA",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_acv_scb",
    "round": 32,
    "home_club_id": "ACV",
    "away_club_id": "SCB",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_csm_cfea",
    "round": 32,
    "home_club_id": "CSM",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j32_slb_rav",
    "round": 32,
    "home_club_id": "SLB",
    "away_club_id": "RAV",
    "kickoff_time": "2027-05-02T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_scp_slb",
    "round": 33,
    "home_club_id": "SCP",
    "away_club_id": "SLB",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_cfea_cdsc",
    "round": 33,
    "home_club_id": "CFEA",
    "away_club_id": "CDSC",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_rav_vsc",
    "round": 33,
    "home_club_id": "RAV",
    "away_club_id": "VSC",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_acv_mfc",
    "round": 33,
    "home_club_id": "ACV",
    "away_club_id": "MFC",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_fcf_cpac",
    "round": 33,
    "home_club_id": "FCF",
    "away_club_id": "CPAC",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_scb_csm",
    "round": 33,
    "home_club_id": "SCB",
    "away_club_id": "CSM",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_alv_est",
    "round": 33,
    "home_club_id": "ALV",
    "away_club_id": "EST",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_fca_gvc",
    "round": 33,
    "home_club_id": "FCA",
    "away_club_id": "GVC",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j33_cdn_fcp",
    "round": 33,
    "home_club_id": "CDN",
    "away_club_id": "FCP",
    "kickoff_time": "2027-05-09T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_csm_alv",
    "round": 34,
    "home_club_id": "CSM",
    "away_club_id": "ALV",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_gvc_cdn",
    "round": 34,
    "home_club_id": "GVC",
    "away_club_id": "CDN",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_slb_fca",
    "round": 34,
    "home_club_id": "SLB",
    "away_club_id": "FCA",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_est_cfea",
    "round": 34,
    "home_club_id": "EST",
    "away_club_id": "CFEA",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_fcp_scb",
    "round": 34,
    "home_club_id": "FCP",
    "away_club_id": "SCB",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_cpac_acv",
    "round": 34,
    "home_club_id": "CPAC",
    "away_club_id": "ACV",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_vsc_fcf",
    "round": 34,
    "home_club_id": "VSC",
    "away_club_id": "FCF",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_cdsc_scp",
    "round": 34,
    "home_club_id": "CDSC",
    "away_club_id": "SCP",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  },
  {
    "id": "g_j34_mfc_rav",
    "round": 34,
    "home_club_id": "MFC",
    "away_club_id": "RAV",
    "kickoff_time": "2027-05-16T00:00:00Z",
    "status": "UPCOMING",
    "home_score": null,
    "away_score": null,
    "result": null
  }
];
